-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ciudades
(
    id_ciudad integer NOT NULL,
    ciudad character varying(100) COLLATE pg_catalog."default" NOT NULL,
    departamento character varying(100) COLLATE pg_catalog."default" NOT NULL,
    code_postal integer NOT NULL,
    CONSTRAINT "Ciudades_pkey" PRIMARY KEY (id_ciudad)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    id_cliente integer NOT NULL,
    id_persona integer NOT NULL,
    fecha_ingreso date NOT NULL,
    calificacion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Cliente_pkey" PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public.cuentas
(
    id_cuenta integer NOT NULL,
    id_cliente integer NOT NULL,
    nrocuenta character varying(500) COLLATE pg_catalog."default" NOT NULL,
    fecha_alta date NOT NULL,
    tipo_cuenta character varying(100) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(100) COLLATE pg_catalog."default" NOT NULL,
    saldo numeric NOT NULL,
    nrocontrato character varying(5000) COLLATE pg_catalog."default" NOT NULL,
    costo_mantenimiento numeric NOT NULL,
    promedio_acreditacion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    moneda character varying(500) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cuentas_pkey PRIMARY KEY (id_cuenta)
);

CREATE TABLE IF NOT EXISTS public.movimientos
(
    id_movimiento integer NOT NULL,
    id_cuenta integer NOT NULL,
    fecha_movimiento date NOT NULL,
    tipo_movimiento character varying COLLATE pg_catalog."default" NOT NULL,
    saldo_anterior numeric NOT NULL,
    saldo_actual numeric NOT NULL,
    monto_movimiento numeric NOT NULL,
    cuenta_origen numeric NOT NULL,
    cuenta_destino numeric NOT NULL,
    canal numeric NOT NULL,
    CONSTRAINT "Movimientos_pkey" PRIMARY KEY (id_movimiento)
);

CREATE TABLE IF NOT EXISTS public.personas
(
    id_personas integer NOT NULL,
    id_ciudad integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tipo_documento character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nro_documento character varying(50) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    celular character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Personas_pkey" PRIMARY KEY (id_personas)
);

ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT "Cliente_id_persona_fkey" FOREIGN KEY (id_persona)
    REFERENCES public.personas (id_personas) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cuentas
    ADD CONSTRAINT cuentas_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.movimientos
    ADD CONSTRAINT "Movimientos_id_cuenta_fkey" FOREIGN KEY (id_cuenta)
    REFERENCES public.cuentas (id_cuenta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personas
    ADD CONSTRAINT "Personas_id_ciudad_fkey" FOREIGN KEY (id_ciudad)
    REFERENCES public.ciudades (id_ciudad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;